/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __edu_osu_cse_ysmart_testquery_ReducerRESQUE__
#define __edu_osu_cse_ysmart_testquery_ReducerRESQUE__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobjectArray JNICALL Java_edu_osu_cse_ysmart_testquery_ReducerRESQUE_intersects (JNIEnv *env, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __edu_osu_cse_ysmart_testquery_ReducerRESQUE__ */

